<?php

namespace Database\Seeders;

use App\Models\Space;
use Illuminate\Database\Seeder;

class SpaceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        Space::create([
            'user_id' => 1,
            'space_type_id' => 1,
            'cancellation_policy_id' => 4,
            'address' => 'QHFV+JM Pissa, Mali',
            'country' => 'Mali',
            'city' => 'Bankass',
            'state' => 'Bankass',
            'postal_code' => '500003',
            'lat' => '13.774066408054827',
            'lng' => '-3.40576171875',
            'allowed_age' => '["All","0 - 10+","40+"]',
            'parking_description' => 'Contracts - Eventopia bookings are covered by our Service Agreement. Do not paste your contract, cancellation policy, or liability policy.',
            'security_devices_description' => 'Contracts - Eventopia bookings are covered by our Service Agreement. Do not paste your contract, cancellation policy, or liability policy.',
            'space_title' => 'Downtown',
            'space_description' => 'Contracts - Eventopia bookings are covered by our Service Agreement. Do not paste your contract, cancellation policy, or liability policy.',
            'space_size' => '220',
            'space_rules' => 'Contracts - Eventopia bookings are covered by our Service Agreement. Do not paste your contract, cancellation policy, or liability policy.',
            'wifi_password' => 'include',
            'arrival_instruction' => 'Contracts - Eventopia bookings are covered by our Service Agreement. Do not paste your contract, cancellation policy, or liability policy.',
            'cleaning_process' => 'Contracts - Eventopia bookings are covered by our Service Agreement. Do not paste your contract, cancellation policy, or liability policy.',
            'last_step' => '10',
            'c_u_fname' => 'Ivory Vega',
            'c_u_lname' => 'Alden Lott',
            'c_u_phone' => '+1 (321) 705-7127',
            'c_u_img' => null,
            'status' => '1',
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        Space::create([
            'user_id' => 1,
            'space_type_id' => 1,
            'cancellation_policy_id' => 4,
            'address' => 'Japan, 〒173-0027 Tokyo, Itabashi City, Minamichō, 18−７ アーバンコート旭',
            'country' => 'Japan',
            'city' => 'Itabashi City',
            'state' => 'Tokyo',
            'postal_code' => '173-0027',
            'lat' => '35.737595151747875',
            'lng' => '139.7021484375',
            'allowed_age' => '["20+","30+","40+"]',
            'parking_description' => 'Contracts - Eventopia bookings are covered by our Service Agreement. Do not paste your contract, cancellation policy, or liability policy.',
            'security_devices_description' => 'Contracts - Eventopia bookings are covered by our Service Agreement. Do not paste your contract, cancellation policy, or liability policy.',
            'space_title' => 'Downtown',
            'space_description' => 'Contracts - Eventopia bookings are covered by our Service Agreement. Do not paste your contract, cancellation policy, or liability policy.',
            'space_size' => '300',
            'space_rules' => 'Contracts - Eventopia bookings are covered by our Service Agreement. Do not paste your contract, cancellation policy, or liability policy.',
            'wifi_password' => 'include',
            'arrival_instruction' => 'Contracts - Eventopia bookings are covered by our Service Agreement. Do not paste your contract, cancellation policy, or liability policy.',
            'cleaning_process' => 'Contracts - Eventopia bookings are covered by our Service Agreement. Do not paste your contract, cancellation policy, or liability policy.',
            'last_step' => '10',
            'c_u_fname' => 'Ivory Vega',
            'c_u_lname' => 'Alden Lott',
            'c_u_phone' => '+1 (321) 705-7127',
            'c_u_img' => null,
            'status' => '1',
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        Space::create([
            'user_id' => 1,
            'space_type_id' => 3,
            'cancellation_policy_id' => 3,
            'address' => '28MV+5F Antioch, NE, USA',
            'country' => 'United States',
            'city' => 'Sheridan County',
            'state' => 'Nebraska',
            'postal_code' => '69340',
            'lat' => '42.032974332441434',
            'lng' => '-102.6562500000001',
            'allowed_age' => '["10+","30+","50+"]',
            'parking_description' => 'Contracts - Eventopia bookings are covered by our Service Agreement. Do not paste your contract, cancellation policy, or liability policy.',
            'security_devices_description' => 'Contracts - Eventopia bookings are covered by our Service Agreement. Do not paste your contract, cancellation policy, or liability policy.',
            'space_title' => 'Loft',
            'space_description' => 'Contracts - Eventopia bookings are covered by our Service Agreement. Do not paste your contract, cancellation policy, or liability policy.',
            'space_size' => '600',
            'space_rules' => 'Contracts - Eventopia bookings are covered by our Service Agreement. Do not paste your contract, cancellation policy, or liability policy.',
            'wifi_password' => null,
            'arrival_instruction' => 'Contracts - Eventopia bookings are covered by our Service Agreement. Do not paste your contract, cancellation policy, or liability policy.',
            'cleaning_process' => 'Contracts - Eventopia bookings are covered by our Service Agreement. Do not paste your contract, cancellation policy, or liability policy.',
            'last_step' => '10',
            'c_u_fname' => 'Ivory Vega',
            'c_u_lname' => 'Alden Lott',
            'c_u_phone' => '+1 (321) 705-7127',
            'c_u_img' => null,
            'status' => '1',
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        Space::create([
            'user_id' => 1,
            'space_type_id' => 4,
            'cancellation_policy_id' => 2,
            'address' => 'G9G8+WV North Bannister WA, Australia',
            'country' => 'Australia',
            'city' => 'Shire of Wandering',
            'state' => 'Western Australia',
            'postal_code' => '6390',
            'lat' => '-32.472695022061494',
            'lng' => '116.3671875',
            'allowed_age' => '["20+","40+","50+"]',
            'parking_description' => 'Contracts - Eventopia bookings are covered by our Service Agreement. Do not paste your contract, cancellation policy, or liability policy.',
            'security_devices_description' => 'Contracts - Eventopia bookings are covered by our Service Agreement. Do not paste your contract, cancellation policy, or liability policy.',
            'space_title' => 'adjective',
            'space_description' => 'Contracts - Eventopia bookings are covered by our Service Agreement. Do not paste your contract, cancellation policy, or liability policy.',
            'space_size' => '400',
            'space_rules' => 'Contracts - Eventopia bookings are covered by our Service Agreement. Do not paste your contract, cancellation policy, or liability policy.',
            'wifi_password' => null,
            'arrival_instruction' => 'Contracts - Eventopia bookings are covered by our Service Agreement. Do not paste your contract, cancellation policy, or liability policy.',
            'cleaning_process' => 'Contracts - Eventopia bookings are covered by our Service Agreement. Do not paste your contract, cancellation policy, or liability policy.',
            'last_step' => '10',
            'c_u_fname' => 'Ulysses Wright',
            'c_u_lname' => 'Ria Sims',
            'c_u_phone' => '+1 (908) 757-2584',
            'c_u_img' => null,
            'status' => '1',
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        Space::create([
            'user_id' => 1,
            'space_type_id' => 5,
            'cancellation_policy_id' => 1,
            'address' => 'W856+G6 Ostapenky, Poltava Oblast, Ukraine',
            'country' => 'Ukraine',
            'city' => 'Khorol\'s\'kyi district',
            'state' => 'Poltava Oblast',
            'postal_code' => '37820',
            'lat' => '49.908787000867186',
            'lng' => '33.310546875000036',
            'allowed_age' => '["10+","20+","30+"]',
            'parking_description' => 'Contracts - Eventopia bookings are covered by our Service Agreement. Do not paste your contract, cancellation policy, or liability policy.',
            'security_devices_description' => 'Contracts - Eventopia bookings are covered by our Service Agreement. Do not paste your contract, cancellation policy, or liability policy.',
            'space_title' => 'View',
            'space_description' => 'Contracts - Eventopia bookings are covered by our Service Agreement. Do not paste your contract, cancellation policy, or liability policy.',
            'space_size' => '500',
            'space_rules' => 'Contracts - Eventopia bookings are covered by our Service Agreement. Do not paste your contract, cancellation policy, or liability policy.',
            'wifi_password' => 'guests',
            'arrival_instruction' => 'Contracts - Eventopia bookings are covered by our Service Agreement. Do not paste your contract, cancellation policy, or liability policy.',
            'cleaning_process' => 'Contracts - Eventopia bookings are covered by our Service Agreement. Do not paste your contract, cancellation policy, or liability policy.',
            'last_step' => '10',
            'c_u_fname' => 'Camille Brooks',
            'c_u_lname' => 'Vernon Mercer',
            'c_u_phone' => '+1 (602) 139-4049',
            'c_u_img' => null,
            'status' => '1',
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        Space::create([
            'user_id' => 1,
            'space_type_id' => 6,
            'cancellation_policy_id' => 2,
            'address' => '4HP3+7V Juanito, Juruá - AM, Brazil',
            'country' => 'Brazil',
            'city' => 'Juruá',
            'state' => 'Amazonas',
            'postal_code' => '69520-000',
            'lat' => '-3.8642546157213955',
            'lng' => '-66.4453125',
            'allowed_age' => '["10+","30+","40+"]',
            'parking_description' => 'Contracts - Eventopia bookings are covered by our Service Agreement. Do not paste your contract, cancellation policy, or liability policy.',
            'security_devices_description' => 'Contracts - Eventopia bookings are covered by our Service Agreement. Do not paste your contract, cancellation policy, or liability policy.',
            'space_title' => 'Example',
            'space_description' => 'Contracts - Eventopia bookings are covered by our Service Agreement. Do not paste your contract, cancellation policy, or liability policy.',
            'space_size' => '565',
            'space_rules' => 'Contracts - Eventopia bookings are covered by our Service Agreement. Do not paste your contract, cancellation policy, or liability policy.',
            'wifi_password' => null,
            'arrival_instruction' => 'Contracts - Eventopia bookings are covered by our Service Agreement. Do not paste your contract, cancellation policy, or liability policy.',
            'cleaning_process' => 'Contracts - Eventopia bookings are covered by our Service Agreement. Do not paste your contract, cancellation policy, or liability policy.',
            'last_step' => '10',
            'c_u_fname' => 'Rooney Berg',
            'c_u_lname' => 'Sopoline Blake',
            'c_u_phone' => '+1 (364) 462-6434',
            'c_u_img' => null,
            'status' => '1',
            'created_at' => now(),
            'updated_at' => now(),
        ]);
    }
}
